language: node_js
node_js: stable
git:
  depth: 1
branches:
  only:
    - master

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build-docs

after_success:
  - cd ./gh-pages
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add .
  - git commit -m "Build docs $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages
# E: Build LifeCycle
