language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - npm run build-docs

after_success:
  - cd ./gh-pages
  - git init
  - git config user.name "meteorlxy"
  - git config user.email "meteor.lxy@foxmail.com"
  - git add .
  - git commit -m "Build docs $(date +%Y%m%d%H%M)"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
    
